### ISSUE TITLE
Responder Topic Lookup Bug on Heroku

### ISSUE THREAD

**Issue by dafeiner** [karafka/karafka#408]
Original error:
```ruby
OrderResponder.call Order.last
```
```
Traceback (most recent call last):
        1: from (irb):25
NoMethodError (undefined method `async?' for nil:NilClass)
```

```ruby
# order_responder.rb
class OrderResponder < ApplicationResponder
  topic :test

  def respond(order)
    respond_to :test, order
  end
end

# karafka.rb

class PrefixTopicMapper
  def initialize(prefix)
    @prefix = prefix
  end

  def incoming(topic)
    topic.to_s.gsub(@prefix, '')
  end

  def outgoing(topic)
    "#{@prefix}#{topic}"
  end
end

class KarafkaApp < Karafka::App
  setup do |config|
    # other setup stuff
    config.topic_mapper = PrefixTopicMapper.new(ENV['KAFKA_PREFIX'])
  end
end

```

It looks like this was broken in #373 ...

When I initialize a new OrderResponder in irb

```
irb(main):010:0> r = OrderResponder.new
=> #<OrderResponder:0x000000000acb1d08 @parser_class=Karafka::Parsers::Json, @messages_buffer={}>
```

Then call the respond_to method directly and look at the messages buffer the topic is namespaced with the prefix (https://github.com/karafka/karafka/blob/b10c4acd2cde4dbf95c524de5088856b5bf1bba0/lib/karafka/base_responder.rb#L194):

```ruby
r.send :respond_to, :test, Order.last
ap r.messages_buffer
{
    "test" => [
        [0] [
            [0] # Order Data,
            [1] {
                :topic => "prefix-123.test"
            }
        ]
    ]
}
```

But the responder topics hash is keyed without the prefix (https://github.com/karafka/karafka/blob/b10c4acd2cde4dbf95c524de5088856b5bf1bba0/lib/karafka/base_responder.rb#L78):

```ruby
irb(main):045:0> ap r.topics
{
    "test" => #<Karafka::Responders::Topic:0x0000000009dce098 @name="test", @options={:registered=>true}>
}
```

So there is a disconnect there. Internally we probably don't want to use the mapped topic name until the very end when we pass it to the `WaterDrop` producer.

I may make a PR later, but it looks like we are at the minimum missing a spec here with prefixed topic names.

**Comment by mensfeld** [comment]
Hello @dafeiner. Thank you for reporting this and really sorry, that you've encountered problems working with Karafka.

It does indeed look like a bug. I'm currently on a short holiday (returning on Sunday), but I've assigned one of the Karafka members, @nijikon to it to coordinate that. 

> I may make a PR later, but it looks like we are at the minimum missing a spec here with prefixed topic names.

Would you be willing to add spec and fix the problem? Or a spec that would show it would be sufficient for @nijikon  to fix that.

**Comment by mensfeld** [comment]
@dafeiner  @nijikon @agwozdowski -the mapper should be used just at the end of everything, right in the moment, we decide to send the messages to Kafka. Good luck and in any case, I will keep an eye on this :)

**Comment by dafeiner** [comment]
@mensfeld @nijikon @agwozdowski 

Add this context to line 235 of `base_responder_spec.rb` to see the failure

```ruby
context 'with a mapped topic' do
  let(:mapped_topic) { "prefix.#{topic_name}" }
  let(:custom_mapper) do
    ClassBuilder.build do
      def self.outgoing(topic)
        "prefix.#{topic}"
      end
    end
  end

  before do
    allow(Karafka::App.config)
      .to receive(:topic_mapper)
      .and_return(custom_mapper)
  end

  let(:topic_name) { rand.to_s }
  let(:message) { { rand.to_s => rand.to_s } }
  let(:working_class) do
    name = topic_name
    ClassBuilder.inherit(described_class) do
      topic name

      define_method :respond do |data|
        respond_to name, data
      end
    end
  end

  it 'sends the message' do
    working_class.call(message)
  end
end
```
